//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CornerBar.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CornerBar.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From tasty homemade food, prepared and cooked by our talented chefs to a selection of specials including:-!CR Paella!CRJuicy Steaks!CRFresh Fish!CRBreakfast from 10am.
        /// </summary>
        internal static string About1 {
            get {
                return ResourceManager.GetString("About1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helen&apos;s world famous Fish &apos;n&apos; Chips can only be eaten on a Wednesday. Using her secret recipe for beer batter, it keeps the crowds coming back in the masses! (Booking advisable).
        /// </summary>
        internal static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We offer our customers... !CR5 HD T.Vs, Free Internet, Sky HD (including BBC, ITV, C4), Pool table, Dart Board, Tennis Court (€10 per hour),Quiz Nights, CashBack, Money Exchange, Mobile Phone Top Up, Take Away Food...!CR.
        /// </summary>
        internal static string About3 {
            get {
                return ResourceManager.GetString("About3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homemade tapas bar in Port Addaia, with the very best fresh ingredients offering delicious &amp; tasty tapas. !CRRecently refurbished with sea view from terrace..
        /// </summary>
        internal static string AboutBlurb {
            get {
                return ResourceManager.GetString("AboutBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are You Sure?.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El Castillo is now in its 11th year, and would like to say a big thank you to all of our customers who have supported us.!CR!CROur food is constantly being improved, our staff are always trying their best to make the whole Castillo experience a memorable one.!CR!CRFrom tasty homemade food, prepared and cooked by our talented chefs to a selection of specials including:-!CR Paella!CRJuicy Steaks!CRFresh Fish!CRBreakfast from 10am!CR!CRWe offer our customers... !CR5 HD T.Vs, Free Internet, Sky HD (including BB [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Blurb1 {
            get {
                return ResourceManager.GetString("Blurb1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !CREverything on our menu is available to take away, You can order by phone and pay on collection.!CR!CRBooking is recommended either by this app, email, phone or good old fashioned coming into the bar.!CR!CRRead the reviews about us on tripadvisor by clicking the tripadvisor logo on our contact page.!CR!CRWe cater for vegeterians and large groups, just drop us a line about specifications.!CR!CRIf you enjoy your experience here please tell your friends - if you don&apos;t PLEASE tell us - Thanks.!CR.
        /// </summary>
        internal static string Blurb2 {
            get {
                return ResourceManager.GetString("Blurb2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book A Table.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book for Fish &apos;n&apos; Chips.
        /// </summary>
        internal static string BookFandC {
            get {
                return ResourceManager.GetString("BookFandC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will send you an email confirming your booking - Thanks!!.
        /// </summary>
        internal static string BookingConf {
            get {
                return ResourceManager.GetString("BookingConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking email sent.
        /// </summary>
        internal static string BookingConfCap {
            get {
                return ResourceManager.GetString("BookingConfCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Date.
        /// </summary>
        internal static string BookingDate {
            get {
                return ResourceManager.GetString("BookingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry - we were unable to email your booking request. Can you try again, or try phoning us - Thanks!!.
        /// </summary>
        internal static string BookingFail {
            get {
                return ResourceManager.GetString("BookingFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking email failed.
        /// </summary>
        internal static string BookingFailCap {
            get {
                return ResourceManager.GetString("BookingFailCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book It!.
        /// </summary>
        internal static string BookIt {
            get {
                return ResourceManager.GetString("BookIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any questions or queries, please don&apos;t hesitate to contact us via email or phone.
        /// </summary>
        internal static string ContactBlurb {
            get {
                return ResourceManager.GetString("ContactBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        internal static string Directions {
            get {
                return ResourceManager.GetString("Directions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email Us .
        /// </summary>
        internal static string emailUS {
            get {
                return ResourceManager.GetString("emailUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !CRWe are open every day except Tuesday from !CR12pm until late!!CR!CR.
        /// </summary>
        internal static string FinalAbout {
            get {
                return ResourceManager.GetString("FinalAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Here .
        /// </summary>
        internal static string GetHere {
            get {
                return ResourceManager.GetString("GetHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GREAT FOOD.
        /// </summary>
        internal static string Head1 {
            get {
                return ResourceManager.GetString("Head1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FISH&apos;N&apos;CHIPS.
        /// </summary>
        internal static string Head2 {
            get {
                return ResourceManager.GetString("Head2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THINGS WE DO.
        /// </summary>
        internal static string Head3 {
            get {
                return ResourceManager.GetString("Head3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry - we only accept bookings between 12pm and 11pm - Thanks.
        /// </summary>
        internal static string InvalidBook {
            get {
                return ResourceManager.GetString("InvalidBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Time.
        /// </summary>
        internal static string InvalidBookCap {
            get {
                return ResourceManager.GetString("InvalidBookCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This doesn&apos;t appear to be a valid email address - are you sure it is correct?.
        /// </summary>
        internal static string Invalidemail {
            get {
                return ResourceManager.GetString("Invalidemail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This doesn&apos;t appear to be a valid phone number - are you sure it is correct?.
        /// </summary>
        internal static string InvalidPhone {
            get {
                return ResourceManager.GetString("InvalidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to book for a !P1 and we are closed on a !P1.
        /// </summary>
        internal static string IsClosed {
            get {
                return ResourceManager.GetString("IsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed !P1.
        /// </summary>
        internal static string IsClosedCap {
            get {
                return ResourceManager.GetString("IsClosedCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi !P4,!CRPlease could I book a table for !P1 people on !P2 at !P3. !CR.
        /// </summary>
        internal static string MailMess {
            get {
                return ResourceManager.GetString("MailMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  and my email address is !P1.
        /// </summary>
        internal static string MailMessEmail {
            get {
                return ResourceManager.GetString("MailMessEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !CRThis is to celebrate !P1.
        /// </summary>
        internal static string MailMessOcc {
            get {
                return ResourceManager.GetString("MailMessOcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !CRMy telephone number is !P1.
        /// </summary>
        internal static string MailMessTel {
            get {
                return ResourceManager.GetString("MailMessTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !CRThank You!CR.
        /// </summary>
        internal static string MailMessThanks {
            get {
                return ResourceManager.GetString("MailMessThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid email address - Thanks.
        /// </summary>
        internal static string MissingEmail {
            get {
                return ResourceManager.GetString("MissingEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing email.
        /// </summary>
        internal static string MissingEmailCap {
            get {
                return ResourceManager.GetString("MissingEmailCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number - Thanks.
        /// </summary>
        internal static string MissingPhone {
            get {
                return ResourceManager.GetString("MissingPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing phone number.
        /// </summary>
        internal static string MissingPhoneCap {
            get {
                return ResourceManager.GetString("MissingPhoneCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasion.
        /// </summary>
        internal static string Occasion {
            get {
                return ResourceManager.GetString("Occasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None|an Anniversary|a Birthday|a Party|a Celebration|an End of holiday meal|a good night out|Other.
        /// </summary>
        internal static string Occasions {
            get {
                return ResourceManager.GetString("Occasions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are open every day except Tuesday from 12pm until late!.
        /// </summary>
        internal static string OpeningTimes {
            get {
                return ResourceManager.GetString("OpeningTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Drinks.
        /// </summary>
        internal static string OrderDrinks {
            get {
                return ResourceManager.GetString("OrderDrinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Address.
        /// </summary>
        internal static string OurAddress {
            get {
                return ResourceManager.GetString("OurAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Menu.
        /// </summary>
        internal static string OurMenu {
            get {
                return ResourceManager.GetString("OurMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuEN1.jpg.
        /// </summary>
        internal static string Page1 {
            get {
                return ResourceManager.GetString("Page1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner Café Bar.
        /// </summary>
        internal static string Page1Desc {
            get {
                return ResourceManager.GetString("Page1Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuEN2.jpg.
        /// </summary>
        internal static string Page2 {
            get {
                return ResourceManager.GetString("Page2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastro Tapas.
        /// </summary>
        internal static string Page2Desc {
            get {
                return ResourceManager.GetString("Page2Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuEN3.jpg.
        /// </summary>
        internal static string Page3 {
            get {
                return ResourceManager.GetString("Page3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mains and Desserts.
        /// </summary>
        internal static string Page3Desc {
            get {
                return ResourceManager.GetString("Page3Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuEN4.jpg.
        /// </summary>
        internal static string Page4 {
            get {
                return ResourceManager.GetString("Page4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vegetarian.
        /// </summary>
        internal static string Page4Desc {
            get {
                return ResourceManager.GetString("Page4Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuEN5.jpg.
        /// </summary>
        internal static string Page5 {
            get {
                return ResourceManager.GetString("Page5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paellas - Rices (Take away available).
        /// </summary>
        internal static string Page5Desc {
            get {
                return ResourceManager.GetString("Page5Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuEN6.jpg.
        /// </summary>
        internal static string Page6 {
            get {
                return ResourceManager.GetString("Page6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bebidas - Drinks - Signature Cocktails.
        /// </summary>
        internal static string Page6Desc {
            get {
                return ResourceManager.GetString("Page6Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of people.
        /// </summary>
        internal static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Us.
        /// </summary>
        internal static string PhoneUS {
            get {
                return ResourceManager.GetString("PhoneUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        internal static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are trying to book a time in the past - unless you are travelling in a DeLorean, please try again - Thanks.
        /// </summary>
        internal static string TooEarly {
            get {
                return ResourceManager.GetString("TooEarly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already Gone.
        /// </summary>
        internal static string TooEarlyCap {
            get {
                return ResourceManager.GetString("TooEarlyCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version !P1!CR!CR.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Site .
        /// </summary>
        internal static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who Are We?.
        /// </summary>
        internal static string WhoAreWe {
            get {
                return ResourceManager.GetString("WhoAreWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YouChose.
        /// </summary>
        internal static string YouChose {
            get {
                return ResourceManager.GetString("YouChose", resourceCulture);
            }
        }
    }
}
